"""add video_filepath to projects

Revision ID: 963e9be672b8
Revises: 9b818d4891ca
Create Date: 2026-03-08 14:38:30.793924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963e9be672b8'
down_revision: Union[str, Sequence[str], None] = '9b818d4891ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('video_filepath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'video_filepath')
    # ### end Alembic commands ###
